baseURL = 'https://www.samlagrave.com/'
title = 'Sam LaGrave'
theme = 'hugo-coder'
languageCode = 'en-us'
defaultcontentlanguage = 'en-us'

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
author = "Sam LaGrave"
info = "Programmer, Language Nerd, Game Designer"
description = "Sam LaGrave's personal website"
avatarurl = "images/avatar.jpg"
colorScheme = "auto"
favicon_16 = "static/favicon.ico"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/SLaGrave/"

[[params.social]]
name = "Linkedin"
icon = "fa-brands fa-linkedin fa-2x"
weight = 2
url = "https://www.linkedin.com/in/sam-lagrave-6350871b4/"

[[params.social]]
name = "Instagram"
icon = "fa-brands fa-instagram fa-2x"
weight = 3
url = "https://www.instagram.com/samlagrave/"

[[menu.main]]
name = "About"
weight = 1
url = "about/"

[[menu.main]]
name = "Projects"
weight = 1
url = "projects/"